web_application/Controllers/TemasController.cs
using BLL;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web_application.Controllers
{
    public class TemasController : Controller
    {
        // GET: Categorias
        public ActionResult Index()
        {
            TemasBLL oBLL = new TemasBLL();
            List<Tema> temas = oBLL.RetrieveAll();
            return View(temas);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tema tema)
        {
            ActionResult Result;
            try
            {
                if (ModelState.IsValid)
                {
                    TemasBLL oBLL = new TemasBLL();
                    oBLL.Create(tema);
                    Result = RedirectToAction("Index");
                }
                else
                {
                    Result = View(tema);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(tema);
            }
        }

        public ActionResult Edit(int id)
        {
            TemasBLL oBLL = new TemasBLL();
            Tema tema = oBLL.Retrieve(id);

            return View(tema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tema tema)
        {
            ActionResult Result;
            try
            {
                if (ModelState.IsValid)
                {
                    TemasBLL oBLL = new TemasBLL();
                    oBLL.Update(tema);
                    Result = RedirectToAction("Index");
                }
                else
                {
                    Result = View(tema);
                }
                return Result;
            }
            catch (Exception e)
            {
                return View(tema);
            }
        }

        public ActionResult Details(int id)
        {
            TemasBLL oBLL = new TemasBLL();
            Tema tema = oBLL.Retrieve(id);

            return View(tema);
        }

        public ActionResult Delete(int id)
        {
            TemasBLL oBLL = new TemasBLL();
            oBLL.Delete(id);
            return RedirectToAction("Index"); //redirecionar al index cuando borres
        }
    }
}

web_application/Views/Temas/Create.cshtml
@model Entities.Tema

@{
    ViewBag.Title = "Nuevo Tema";
}

<h2>Nuevo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tema</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NombreTema, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreTema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreTema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

web_application/Views/Temas/Details.cshtml
@model Entities.Tema
@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<dl class="dl-horizontal">
 
    <dt>
        Nombre
    </dt>

    <dd>
        @Html.DisplayFor(model => model.NombreTema)
    </dd>


</dl>

<a href="@Url.Action("Edit", "Temas",new { id=Model.TemaID})" class="btn btn-circle green-meadow btn-sm">
    <icon class="fa fa-pencil"></icon> Editar
</a>

<a href="@Url.Action("Delete", "Temas",new { id=Model.TemaID})" class="btn btn-circle red btn-sm">
    <icon class="fa fa-trash"></icon> Eliminar
</a>

@Html.ActionLink("Editar", "Edit", new { id = Model.TemaID }, new { @class = "btn btn-primary" }) &nbsp;
@Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-success" }) &nbsp;
@Html.ActionLink("Lista de Temas", "Index", null, new { @class = "btn btn-white" })

web_application/Views/Temas/Edit.cshtml
@model Entities.Tema

@{
    ViewBag.Title = "Editar Tema";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tema</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TemaID)

        <div class="form-group">
            @Html.LabelFor(model => model.NombreTema, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreTema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreTema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

web_application/Views/Temas/Index.cshtml
@model IEnumerable<Entities.Tema>

@{
    ViewBag.Title = "Lista de Temas";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box white ">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Temas
                </div>
                <div class="actions">
                    <a href="@Url.Action("Create", "Temas")" class="btn btn-outline btn-circle green-meadow btn-sm">
                        <icon class="fa fa-plus"></icon> Agregar
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover table-header-fixed" id="sample_2">
                    <thead>
                        <tr>
                            <th> Tema </th>
                            <th> Acciones </th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th> Tema </th>
                            <th> Acciones </th>
                        </tr>
                    </tfoot>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NombreTema)
                                </td>
                               
                                <td>
                                    
                                            <a href="@Url.Action("Details", "Temas",new { id=item.TemaID})" class="btn btn-circle blue btn-sm">
                                                <icon class="fa fa-info"></icon> Detalles
                                            </a>
                                     
                                           
                                       
                                    </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>